export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

export const ADD_USER = "ADD_USER";
export const EDIT_USER = "EDIT_USER";
export const DELETE_USER = "DELETE_USER";
export const SHOW_USERS = "SHOW_USERS";
export const SEARCH_USERS = "SEARCH_USERS";

export const ADD_GROUP = "ADD_GROUP";
export const EDIT_GROUP = "EDIT_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const SHOW_GROUPS = "SHOW_GROUPS";
export const SEARCH_GROUPS = "SEARCH_GROUPS";

export const ADD_ATTRIBUTE = "ADD_ATTRIBUTE";
export const EDIT_ATTRIBUTE = "EDIT_ATTRIBUTE";
export const DELETE_ATTRIBUTE = "DELETE_ATTRIBUTE";
export const SHOW_ATTRIBUTES = "SHOW_ATTRIBUTES";
export const SEARCH_ATTRIBUTES = "SEARCH_ATTRIBUTES";
