import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import { Provider } from "react-redux";
import reducer from "./redux/reducers/rootReducer";
import { createStore } from "redux";
import * as serviceWorker from './serviceWorker';
const store = createStore(reducer);
ReactDOM.render( <Provider store={store}><App /></Provider>, document.getElementById('root'));
serviceWorker.unregister();
